SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480

SCREEN_TITLE = 'Megaman 1'

COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)

MEGAMAN_WALKING_SPRITE_SHEET = 'assets/megaman_walking.png'
MEGAMAN_WALKING_SPRITE_SHEET_SIZE = 9
MEGAMAN_WALKING_SPRITE_WIDTH = 64
MEGAMAN_WALKING_SPRITE_HEIGHT = 64

MEGAMAN_SHOOTING_SPRITE_SHEET = 'assets/megaman_shooting.png'
MEGAMAN_SHOOTING_SPRITE_SHEET_SIZE = 9
MEGAMAN_SHOOTING_SPRITE_WIDTH = 64
MEGAMAN_SHOOTING_SPRITE_HEIGHT = 64

MEGAMAN_JUMPING_SPRITE_SHEET = 'assets/megaman_jumping.png'
MEGAMAN_JUMPING_SPRITE_SHEET_SIZE = 9
MEGAMAN_JUMPING_SPRITE_WIDTH = 64
MEGAMAN_JUMPING_SPRITE_HEIGHT = 64